project:  
  type: website
  render: 
    - "*.qmd"
    - "!archive_2425/*"
  output-dir: ../docs/2526/labs

website:
  title: "DAPR2"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents: 
        - text: "Flashcards"
          href: 1_b2_reading.qmd
          
        - section: "Semester 1"
          contents: 
          
            - section: "Intro to Linear Models"
              contents:
                   - 1_01_slr.qmd
                   - 1_02_mlr.qmd            
                   - 1_03_mlr_stz.qmd
                   - 1_04_model_fit_comp.qmd
                   - 1_05_writeup_recap1.qmd
                
            - section: "Analysing and Evaluating Experimental Studies"
              contents:
                   - 1_06_dummy.qmd
                   - 1_07_effects.qmd
                   - 1_08_assump_diag.qmd
                   - 1_09_bootstrap.qmd
                   - 1_10_writeup_recap2.qmd
                  
        - section: "Semester 2"
          contents: 
          
            - section: "Interaction Models"
              contents:
                # - 2_01_int1_nc.qmd              
                # - 2_02_int2_nn.qmd
                # - 2_03_int3_cc.qmd
                # - 2_04_simp_pair.qmd
                # - 2_05_writeup_recap3.qmd

            - section: "Advanced Topics for LM"
              contents:
                # - 1_b4_reading.qmd              
                # - 2_06_power.qmd              
                # - 2_07_glm1.qmd
                # - 2_08_glm2.qmd
                # - 2_09_writeup_recap4.qmd
                  
                  
bibliography: biblio.bib

format:
  html:
    toc: true
    toc_float: true
    code-annotations: hover
    link-citations: true
    theme: 
      - united
      - assets/style-labs.scss
    include-in-header: 
      - "assets/toggling.html"
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    number-sections: false
    code-link: true
 